name: 更新 CHANGELOG

on:
  push:
    tags:
      - "v*"  # 仅在推送 tag 时触发，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v4

      - name: 获取当前版本 Tag 和上一个 Tag
        id: tags
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))
          echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

      - name: 生成更新日志
        id: changelog
        run: |
          echo "## ✨ ${{ steps.tags.outputs.current_tag }} ($(date '+%Y-%m-%d'))" > NEW_CHANGELOG.md
          echo "" >> NEW_CHANGELOG.md
          git log ${{ steps.tags.outputs.previous_tag }}..${{ steps.tags.outputs.current_tag }} --pretty=format:"* %s" >> NEW_CHANGELOG.md
          echo -e "\n---\n" >> NEW_CHANGELOG.md
          cat CHANGELOG.md >> NEW_CHANGELOG.md
          mv NEW_CHANGELOG.md CHANGELOG.md

      - name: 提交更新日志
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "自动更新 CHANGELOG.md for ${{ steps.tags.outputs.current_tag }}"
          git push origin HEAD:main
